<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RpcSample</RootNamespace>
    <Authors>Michael Lakerveld</Authors>
    <Company>Lakerfield B.V.</Company>
    <Product>Lakerfield.Rpc</Product>
    <Copyright>Lakerfield B.V.</Copyright>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lakerfield.Rpc.WebSocketClient\Lakerfield.Rpc.WebSocketClient.csproj" />
    <ProjectReference Include="..\Lakerfield.Rpc.SourceGenerator\Lakerfield.Rpc.SourceGenerator.csproj" PrivateAssets="all" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\RpcSample\RpcSample.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Persist the source generator (and other) files to disk (https://andrewlock.net/creating-a-source-generator-part-6-saving-source-generator-output-in-source-control/) -->
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <!-- The "base" path for the source generators -->
    <GeneratedFolder>Generated</GeneratedFolder>
    <!-- Write the output for each target framework to a different sub-folder -->
    <CompilerGeneratedFilesOutputPath>$(GeneratedFolder)\$(TargetFramework)</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <!-- Exclude everything in the generated folder for compilation -->
    <Compile Remove="$(GeneratedFolder)/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <!-- Show excluded in solution explorer -->
    <None Include="$(GeneratedFolder)/**/*.cs" />
  </ItemGroup>

</Project>
