name: Build .NET Core and publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.0
      with:
          versionSpec: '5.8.x'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v3.2.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: 8.0.408
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore  /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.Sha }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack Rpc with dotnet
      run: dotnet pack --no-restore --no-build src/Lakerfield.Rpc/Lakerfield.Rpc.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.semVer }}
    - name: Pack Rpc.Client with dotnet
      run: dotnet pack --no-restore --no-build src/Lakerfield.Rpc.Client/Lakerfield.Rpc.Client.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.semVer }}
    - name: Pack Rpc.Server with dotnet
      run: dotnet pack --no-restore --no-build src/Lakerfield.Rpc.Server/Lakerfield.Rpc.Server.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.semVer }}
    - name: Pack Rpc.WebSocketClient with dotnet
      run: dotnet pack --no-restore --no-build src/Lakerfield.Rpc.WebSocketClient/Lakerfield.Rpc.WebSocketClient.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.semVer }}
    - name: Pack Rpc.WebSocketServer with dotnet
      run: dotnet pack --no-restore --no-build src/Lakerfield.Rpc.WebSocketServer/Lakerfield.Rpc.WebSocketServer.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.semVer }}
    - name: Pack Rpc.SourceGenerator with dotnet
      run: dotnet pack --no-restore --no-build src/Lakerfield.Rpc.SourceGenerator/Lakerfield.Rpc.SourceGenerator.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.semVer }}
    - name: Push with dotnet
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json